<!DOCTYPE html>
<?php
	//To prevent cache from storing the website: (from http://docstore.mik.ua/orelly/webprog/php/ch07_05.htm)
	header("Cache-Control: no-cache, no-store, must-revalidate"); // HTTP 1.1.
	header("Pragma: no-cache"); // HTTP 1.0.
	header("Expires: 0"); // Proxies.
?>
<html>
   <head>
      <title>ProteoSign help page</title>
      <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
      <meta charset="UTF-8">
      <style>
        #main_div
        {
          display: block;
          margin: 0 20%;
          width: 1024px;
          margin-top: 50px;
          font-family: 'Segoe UI';
          font-weight: 300;
          font-size: 18px;
        }
        .dl-horizontal dt {
            white-space: normal;
            margin-top: 25%;
            font-family: 'Segoe UI';
            font-weight: normal;
            font-size: 16px;
            width: 40%;
            text-align: left;
        }
        .dl-horizontal dd
        {
          border-left: 1px dashed grey;
          padding-left: 3%;
          margin-bottom: 50px;
          margin-left: 42%;
        }
        h3 {
            text-decoration: underline;
        }
      </style>
	  <link rel="shortcut icon" href="favicon.ico" type="image/x-icon">
   </head>
   <body>
      <div id="main_div">
        <div style="width: 100%; margin: 0 auto;">
        Dear user,
        <br><br>below you will find a list of screenshots taken from the ProteoSign website, accompanied with a brief description. In some cases, additional helpful information can be found inside the corresponding page. For more details please refer to the article.
        <br><br>The ProteoSign Team.
        </div>
        <dl class="dl-horizontal" style="margin-top: 100px">
            <dt><h3>Welcome page</h3>
              Basic description of the platform. Clicking the <i>Start</i> button takes the user to the next page.
            </dt>
            <dd><img src="images/scrshot1.PNG"/></dd>
            <dt><h3>Software input definition page</h3>
              The first step of any data analysis: defining the input data set. The input can either be uploaded via the <i>Upload file(s)</i> button or, just for demonstration pupropses, be selected from pre-uploaded files by clicking the <i>choose</i> hyperlink.
              <br><br>
              <span style="text-decoration: underline">Data file format:</span>
              <br>ProteoSign accepts Proteome Discoverer or MaxQuant output data. For the case of MaxQuant, one has to simply upload the automatically generated <i>proteinGroups</i> and <i>evidence</i> output files. For the case of Proteome Discoverer, the output required is a single file, but it is not automatically generated and thus has to be generated by the user. This process is described inside a pop-up dialog which shows up when the user hovers the mouse over the blue-colored question mark. For the sake of completeness, the contents of that dialog, i.e. the description of the procedure, is shown below.
            </dt>
            <dd><img src="images/scrshot2.PNG"/></dd>
            <dt><h3>Proteome Discoverer output file generation</h3>
              The <em>peptide spectrum match</em> (PSM) file, comprising the necessary information required for protein quantitation, has to be produced manually through the PD desktop application (see the <em>Export&#x2192;To Text</em> option under the <em>File</em> menu).</p><p>The PSM file must be created from within a PD report which combines the information from all relevant MS analyses (i.e. replicates, conditions etc). Such a PD report is sometimes required to be created based on separate reports and is referred to as a multi-consensus report.</p><p>Before exporting the information, one <strong>must</strong> firstly disable peptide grouping (see relevant screen in Figure 1 on the right) and secondly edit the report's <em>Quantification Method</em> by configuring the <em>Ratio&nbsp;Calculation</em> parameters as shonw in the relevant screen in Figure 2 on the right.</p>
            </dt>
            <dd>
              <figure style="width: 77%">
                <img src="images/pdpepgroup.png" style="width: 100%;"/>
                <figcaption style="text-align: center;">Figure 1. Disabling peptide grouping.</figcaption>
              </figure>
              <figure style="width: 77%; margin-top: 30px">
                <img src="images/pdquantmeth.png" style="width: 100%;"/>
                <figcaption style="text-align: center;">Figure 2. Editing ratio calculation parameters.</figcaption>
              </figure>
            </dd>
            <dt><h3>Pre-defined input dialog</h3>
              By clicking the aforementioned hyperlink <i>choose</i>, a dialog shows up, listing the available demo data sets. The user can select a data set and click <i>OK</i>, as well as, for inspection purposes, download it by clicking <i>Download</i>.
            </dt>
            <dd><img src="images/scrshot3.PNG"/></dd>
            <dt><h3>Software input definition page (continued)</h3>
              Once the input is defined, the software performs a pre-processing step, where the data set is validated. If no error occurs, the user is taken to the next page (see below).
            </dt>
            <dd><img src="images/scrshot3_1.PNG"/></dd>
            <dt><h3>Experimental design definition page</h3>
              Here the user must define the experimental structure, i.e. which measurements belong to a certain biological or technical replicate. In a biological treatments-multiplexed proteomics experiment, the measurements/data for each biological or technical replicate, or chromatographic fraction, are contained in single <i>raw</i> file.
              <br><br>
              The table in this page lists the raw files generated in the experiment and the user must <i>assign</i> here the replicate information for every single one of them. In the figure on the right this assignment is automatically performed by the software since a demo data set was selected for analysis.
            </dt>
            <dd><img src="images/scrshot4.PNG"/></dd>
            <dt><h3>Experimental design definition page (continued)</h3>
              In the case of user-uploaded data (and not demo data), the figure on the right illustrates the replicate assignment procedure: the user first selects the table rows (i.e. raw files) and then types in the <i>Experimental structure coordinate</i> panel the corresponding biological and/or technical replicate.
              <br><br>
              Usage note: When multiple raw files are selected, if just the biological replicate is entered, the software will assume that the selected raw files are technical replicates of the entered biological replicate. If both the biological and technical replicates are entered, the software will assume that the selected raw files are fractions of the entered technical replicate.
            </dt>
            <dd><img src="images/scrshot5.PNG"/></dd>
            <dt><h3>Experimental parameters definition page</h3>
              Here the user can enter some meta information regarding the experiment (<i>Experiment ID</i> and <i>Experiment description</i>) but most importantly choose the set of biological conditions/treatments to compare against each other. Typically all conditions are selected here via the <i>Conditions to compare</i> list. The <i>advanced parameters</i> section comprises options for filtering-out certain kinds of measurements. More details can be found by hovering the mouse over the question mark icon (at the actual page).
              <br><br>
              By clicking <i>Submit</i> the user initiates the statistical analysis.
            </dt>
            <dd><img src="images/scrshot6.PNG"/></dd>
            <dt><h3>Statistical analysis wait page</h3>
              Here the user waits for the software to finish the statistical analysis, while presented with current <i>Nature Methods</i> articles hyperlinks. When the analysis is finished, the user is navigated automatically to the next page (see below).
            </dt>
            <dd><img src="images/scrshot7.PNG"/></dd>
            <dt><h3>Statistical analysis results preview page</h3>
              Here the user can preview the analysis output in the form of representative key data plots. The button <i>Next</i> takes the user to the final page.
            </dt>
            <dd><img src="images/scrshot8.PNG"/></dd>
            <dt><h3>Final page</h3>
              Here the user can click on the <i>proteosign.zip</i> hyperlink to download the entire software output, comprising the aforementioned data plots, other diagnostic plots and various data tables in the form of text files (see below).
            </dt>
            <dd><img src="images/scrshot9.PNG"/></dd>
            <dt><h3>Sofware output files</h3>
              The figure on the right shows the output files generated for the demo data set used throughput this Help page. The <i>PDF</i> files contain the the aforementioned plots. For each of the text files, a brief description is provided below.
            </dt>
            <dd><img src="images/scrshot10.PNG"/></dd>
            <dt><h3>Log file</h3>
              This file is generated by the core statistical analysis R script and can be used by the software authors for troubleshooting in problematic cases.
            </dt>
            <dd><img src="images/scrshot11.PNG"/></dd>
            <dt><h3>condition-i vs condition-j file</h3>
              This table constitutes part of the core output of the statistical analysis software (LIMMA). For each protein, it shows:
              <br><br>Column <i>A</i>: the average log2 intensity across conditions and replicates.
              <br>Column <i>Coef</i>: the estimate of the log2-fold-change.
              <br>Column <i>t</i>: the moderated t-statistic.
              <br>Column <i>p.value</i>: the raw p-value corresponding to the t-statistic.
              <br>Column <i>p.value.adj</i>: the adjusted p-value.
              <br>Column <i>F</i>: the moderated F-statistic.
              <br>Column <i>F.p.value</i>: the p-value corresponding to the F-statistic.
            </dt>
            <dd><img src="images/scrshot12.PNG"/></dd>
            <dt><h3>Blocking variable file</h3>
              Indicates the technical replicates in the design matrix file (described below). This file is for diagnostic purposes only.
            </dt>
            <dd><img src="images/scrshot13.PNG"/></dd>
            <dt><h3>Design matrix file</h3>
              Table showing the contents of the design matrix. This file is for diagnostic purposes only.
            </dt>
            <dd><img src="images/scrshot20.PNG"/></dd>
            <dt><h3>Contrasts matrix file</h3>
              Specifies which comparisons between the linear model coefficients are of interest. This file is for diagnostic purposes only.
            </dt>
            <dd><img src="images/scrshot14.PNG"/></dd>
            <dt><h3>Quantified proteins list file</h3>
              Table listing the proteins quantified in each biological replicate. Can be used to construct a Venn diagram.
            </dt>
            <dd><img src="images/scrshot15.PNG"/></dd>
            <dt><h3>LIMMA input file</h3>
              Table showing the post-processed (log2-transformed and quantile-normalized) data that were sent for analysis to the core statistics software (LIMMA). This file is for diagnostic purposes only.
            </dt>
            <dd><img src="images/scrshot16.PNG"/></dd>
            <dt><h3>LIMMA early input file</h3>
              Table showing the pre-processed data that were sent for analysis to the core statistics software (LIMMA). This file is for diagnostic purposes only.
            </dt>
            <dd><img src="images/scrshot21.PNG"/></dd>
            <dt><h3>Identified proteins list file</h3>
              Table listing the proteins identified in each biological replicate. Can be used to construct a Venn diagram.
            </dt>
            <dd><img src="images/scrshot17.PNG"/></dd>
            <dt><h3>Results file</h3>
              The statistical analysis main output file. For each protein, information about the expression ratio between conditions and its significance level are given.
            </dt>
            <dd><img src="images/scrshot18.PNG"/></dd>
            <dt><h3>Top results file</h3>
              A trimmed version of the aforementioned results file comprising only the statistically significant results (differentially expressed protiens).
            </dt>
            <dd><img src="images/scrshot19.PNG"/></dd>
            <dt><h3>Pre-normalization intensities PDF file</h3>
              Box plots of log2 protein intensities before quantile normalization for each replicate and condition.
            </dt>
            <dd><img src="images/scrshot22.PNG"/></dd>
            <dt><h3>Post-normalization intensities PDF file</h3>
              Box plots of log2 protein intensities after quantile normalization for each replicate and condition.
            </dt>
            <dd><img src="images/scrshot23.PNG"/></dd>
            <dt><h3>Log2-fold change histogram PDF file</h3>
              Histogram of Log2 protein intensity ratio.
            </dt>
            <dd><img src="images/scrshot24.PNG"/></dd>
            <dt><h3>MA plot PDF file</h3>
              Scatter plot of average log2 protein intensity ratio against average log2 intensity (also known as MA plot).
            </dt>
            <dd><img src="images/scrshot25.PNG"/></dd>
            <dt><h3>Intensities scatter plot matrix PDF file</h3>
              Scatter plots and linear regression lines, histograms, and R-squared values for each combination of replicate log2 protein intensity ratio.
            </dt>
            <dd><img src="images/scrshot26.PNG"/></dd>
            <dt><h3>Value-ordered fold change PDF file</h3>
              Plot of Protein number (ID) against log2 intensity ratio.
            </dt>
            <dd><img src="images/scrshot27.PNG"/></dd>
            <dt><h3>Volcano plot PDF file</h3>
              Plot of average log2 protein intensity ratio against -log10 p-value (also known as volcano plot) .
            </dt>
            <dd><img src="images/scrshot28.PNG"/></dd>
        </dl>
      </div>
   </body>
</html>
