ratios.hist.colour<-"cyan"
reps.scatter.lmline.colour<-"red"
nRequiredLeastBioreps<-2
GUI<-F
paramssetfromGUI<-F
keepEvidenceIDs<-F
exportFormat<-"pdf"
rep_order<-NA
mqValidation<-F
working_directory<-getwd()
pgroups_fname<-"Dimethyl_MQ_proteinGroups.txt"
evidence_fname<-"Dimethyl_MQ_evidence.txt"
outputFigsPrefix<-"msdiffexp_test"
filterL_lbl<-"L"
bioreps<-3
filterL_lvl<-F
LabelFree<-F
PDdata<-F
time.point<-"2h"
techreps<-c(18,22,23)
ProteinQuantitation<-T
filterL<-F
addLabel("L",c(""))
addLabel("H",c(""))

