ratios.hist.colour<-"cyan"
reps.scatter.lmline.colour<-"red"
nRequiredLeastBioreps<-2
GUI<-F
paramssetfromGUI<-F
keepEvidenceIDs<-F
exportFormat<-"pdf"
rep_order<-NA
mqValidation<-F
working_directory<-getwd()
pgroups_fname<-"Dimethyl_DIC_merged_psms.txt"
evidence_fname<-"Dimethyl_DIC_merged_psms.txt"
outputFigsPrefix<-"msdiffexp_test"
filterL_lbl<-"Light"
bioreps<-3
filterL_lvl<-F
LabelFree<-F
PDdata<-T
time.point<-"2h"
techreps<-1
ProteinQuantitation<-T
filterL<-F
addLabel("Light",c("Dimethyl"))
addLabel("Medium",c("2H(4)"))
experimental_structure_file<-"Dimethyl_DIC_PD_exp_struct.txt"