ratios.hist.colour<-"cyan"
reps.scatter.lmline.colour<-"red"
nRequiredLeastBioreps<-2
GUI<-F
paramssetfromGUI<-F
keepEvidenceIDs<-F
exportFormat<-"pdf"
rep_order<-NA
mqValidation<-F
working_directory<-getwd()
pgroups_fname<-"Dimethyl_PD_psms.txt"
evidence_fname<-"Dimethyl_PD_psms.txt"
outputFigsPrefix<-"a"
filterL_lbl<-"Light"
filterL_lvl<-F
PDdata<-T
time.point<-"a"
LabelFree<-F
ProteinQuantitation<-T
filterL<-F
addLabel("Light",c("Dimethyl"))
addLabel("Medium",c("2H(4)"))
experimental_structure_file<-"Dimethyl_PD_exp_struct.txt"
