ratios.hist.colour<-"cyan"
reps.scatter.lmline.colour<-"red"
nRequiredLeastBioreps<-2
GUI<-F
paramssetfromGUI<-F
keepEvidenceIDs<-F
exportFormat<-"pdf"
rep_order<-NA
mqValidation<-F
working_directory<-getwd()
pgroups_fname<-"PD_psms.txt"
evidence_fname<-"PD_psms.txt"
outputFigsPrefix<-"msdiffexp_test"
filterL_lbl<-"Light"
filterL_lvl<-F
PDdata<-T
time.point<-"2h"
ProteinQuantitation<-T
filterL<-F
addLabel("Light",c(""))
addLabel("Medium",c("2H(4)","13C(6)"))
addLabel("Heavy",c("13C(6)15N(2)","13C(6)15N(4)"))
experimental_structure_file<-"exp_struct.txt"
