ratios.hist.colour<-"cyan"
reps.scatter.lmline.colour<-"red"
nRequiredLeastBioreps<-2
GUI<-F
paramssetfromGUI<-F
keepEvidenceIDs<-F
exportFormat<-"pdf"
rep_order<-NA
mqValidation<-F
#working_directory<-"msdiffexp_wd"
pgroups_fname<-"MQ_proteinGroups.txt"
evidence_fname<-"MQ_evidence.txt"
outputFigsPrefix<-"pSILAC_3_plex_MQ_"
filterL_lbl<-"L"
bioreps<-3
filterL_lvl<-F
LabelFree<-F
PDdata<-F
time.point<-"4h"
techreps<-3
ProteinQuantitation<-T
filterL<-F
addLabel("M",c(""))
addLabel("H",c(""))
